name: docker-devops-lessons

services:
  db:
    image: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: devops
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin
    networks:
      - mynetwork

  backend:
    build:
      context: DevopsClass
    restart: always
    environment:
      MYSQL_HOST: db
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: devops
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin
    depends_on:
      - db
    networks:
      - mynetwork
    ports:
      - "8000:8000"

  frontend:
    build:
      context: DevopsClassFront/dist
    restart: always
    ports:
      - "80:80"

networks:
  mynetwork:
    driver: bridge
